package adapter

import (
	"io"
	"strings"

	"github.com/k1wi777/my-harness-SDD/internal/paths"
)

// claudeMark identifica los archivos generados por el adaptador de Claude Code.
const claudeMark = "<!-- GENERATED by rei — no editar; regenerar con `rei init claude` -->"

// validClaudeTools son las herramientas nativas admitidas en el frontmatter de
// un agente de Claude Code.
var validClaudeTools = map[string]bool{
	"Read":  true,
	"Write": true,
	"Edit":  true,
	"Grep":  true,
	"Glob":  true,
	"Bash":  true,
	"Agent": true,
}

// claudeAgentData son los datos que consume agent.tmpl de Claude Code.
type claudeAgentData struct {
	Name        string
	Description string
	Tools       string
	Model       string
	Mark        string
	Contract    string
}

// claudeRuntime es el descriptor del runtime Claude Code.
var claudeRuntime = runtime{
	name:         "claude",
	hostedDir:    ".claude/agents",
	mark:         claudeMark,
	nativeKey:    "tools",
	validTargets: validClaudeTools,
	buildData: func(role Role, targets []string) any {
		return claudeAgentData{
			Name:        role.Name,
			Description: role.Description,
			Tools:       strings.Join(targets, ", "),
			Model:       role.Model,
			Mark:        claudeMark,
			Contract:    "## Contrato\n\n" + role.Contract,
		}
	},
}

// InstallClaude despliega el esqueleto y genera los agentes nativos de Claude
// Code en .claude/agents/<rol>.md. Devuelve 1 si alguna fase falla.
func InstallClaude(p *paths.Project, out io.Writer) int { return install(p, claudeRuntime, out) }

// CheckClaude verifica, sin escribir, los agentes nativos de Claude Code.
// Devuelve 0 si todo coincide y 1 si falta, no lleva la marca o difiere algún
// archivo.
func CheckClaude(p *paths.Project, out io.Writer) int { return check(p, claudeRuntime, out) }
