package adapter

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/k1wi777/my-harness-SDD/internal/paths"
)

// generatedMark identifica los archivos generados por el adaptador y es lo que
// autoriza a sobrescribirlos. Es una constante del paquete (no de la
// plantilla) para que no pueda olvidarse al personalizar el adaptador.
const generatedMark = "<!-- GENERATED by rei — no editar; regenerar con `rei init opencode` -->"

// validPermissions son las claves de permiso aceptadas en el frontmatter nativo
// de OpenCode V2.
var validPermissions = map[string]bool{
	"read": true,
	"edit": true,
	"glob": true,
	"grep": true,
	"bash": true,
	"task": true,
}

// toolEntry es una entrada de tools.json.
type toolEntry struct {
	Permission []string `json:"permission"`
}

// toolMap es el contenido de tools.json: herramienta genérica -> claves de
// permiso de OpenCode.
type toolMap map[string]toolEntry

// Permission es una entrada `clave: allow` del mapa `permission` nativo.
type Permission struct {
	Key   string
	Value string
}

// agentData son los datos que consume agent.tmpl.
type agentData struct {
	Description string
	Mode        string
	Model       string
	Permissions []Permission
	Mark        string
	Contract    string
}

// opencodeDir es el directorio del adaptador dentro del proyecto destino.
func opencodeDir(p *paths.Project) string {
	return filepath.Join(p.ReiDir(), "adapters", "opencode")
}

// loadToolMap lee y valida .rei/adapters/opencode/tools.json.
func loadToolMap(p *paths.Project) (toolMap, error) {
	data, err := os.ReadFile(filepath.Join(opencodeDir(p), "tools.json"))
	if err != nil {
		return nil, fmt.Errorf("no se pudo leer tools.json del adaptador: %w", err)
	}
	var tm toolMap
	if err := json.Unmarshal(data, &tm); err != nil {
		return nil, fmt.Errorf("tools.json inválido: %w", err)
	}
	if err := validateToolMap(tm); err != nil {
		return nil, err
	}
	return tm, nil
}

// validateToolMap exige que el mapa cubra todas las herramientas genéricas y
// que cada valor sea una clave de permiso válida.
func validateToolMap(tm toolMap) error {
	generics := make([]string, 0, len(genericTools))
	for tool := range genericTools {
		generics = append(generics, tool)
	}
	sort.Strings(generics)
	for _, tool := range generics {
		if _, ok := tm[tool]; !ok {
			return fmt.Errorf("tools.json no cubre la herramienta genérica %q", tool)
		}
	}
	for _, tool := range sortedKeys(tm) {
		entry := tm[tool]
		if len(entry.Permission) == 0 {
			return fmt.Errorf("tools.json: %q no declara ninguna clave de permiso", tool)
		}
		for _, perm := range entry.Permission {
			if !validPermissions[perm] {
				return fmt.Errorf("tools.json: clave de permiso desconocida %q para %q", perm, tool)
			}
		}
	}
	return nil
}

func sortedKeys(tm toolMap) []string {
	keys := make([]string, 0, len(tm))
	for key := range tm {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// buildPermissions traduce las herramientas genéricas del rol a un mapa
// `permission` ordenado según la declaración de `tools`, deduplicando claves
// (write y edit colapsan en `edit`).
func buildPermissions(tools []string, tm toolMap) ([]Permission, error) {
	var out []Permission
	seen := map[string]bool{}
	for _, tool := range tools {
		entry, ok := tm[tool]
		if !ok {
			return nil, fmt.Errorf("herramienta genérica sin mapeo en tools.json: %q", tool)
		}
		for _, perm := range entry.Permission {
			if seen[perm] {
				continue
			}
			seen[perm] = true
			out = append(out, Permission{Key: perm, Value: "allow"})
		}
	}
	return out, nil
}

// renderAgent construye el archivo nativo de OpenCode para un rol: frontmatter
// mapeado, marca GENERATED y el ## Contrato como cuerpo.
func renderAgent(p *paths.Project, role Role) (string, error) {
	raw, err := os.ReadFile(filepath.Join(opencodeDir(p), "agent.tmpl"))
	if err != nil {
		return "", fmt.Errorf("no se pudo leer agent.tmpl del adaptador: %w", err)
	}
	tmpl, err := template.New("agent").Parse(string(raw))
	if err != nil {
		return "", fmt.Errorf("agent.tmpl inválido: %w", err)
	}
	tm, err := loadToolMap(p)
	if err != nil {
		return "", err
	}
	perms, err := buildPermissions(role.Tools, tm)
	if err != nil {
		return "", err
	}
	data := agentData{
		Description: role.Description,
		Mode:        role.Mode,
		Model:       role.Model,
		Permissions: perms,
		Mark:        generatedMark,
		Contract:    "## Contrato\n\n" + role.Contract,
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("no se pudo aplicar agent.tmpl: %w", err)
	}
	return buf.String(), nil
}
