package adapter

import (
	"io"

	"github.com/k1wi777/my-harness-SDD/internal/paths"
)

// generatedMark identifica los archivos generados por el adaptador de OpenCode
// y es lo que autoriza a sobrescribirlos. Es una constante del paquete (no de
// la plantilla) para que no pueda olvidarse al personalizar el adaptador.
const generatedMark = "<!-- GENERATED by rei — no editar; regenerar con `rei init opencode` -->"

// validPermissions son las claves de permiso aceptadas en el frontmatter nativo
// de OpenCode V2.
var validPermissions = map[string]bool{
	"read": true,
	"edit": true,
	"glob": true,
	"grep": true,
	"bash": true,
	"task": true,
}

// Permission es una entrada `clave: allow` del mapa `permission` nativo de
// OpenCode.
type Permission struct {
	Key   string
	Value string
}

// agentData son los datos que consume agent.tmpl de OpenCode.
type agentData struct {
	Description string
	Mode        string
	Model       string
	Permissions []Permission
	Mark        string
	Contract    string
}

// opencodeRuntime es el descriptor del runtime OpenCode V2.
var opencodeRuntime = runtime{
	name:         "opencode",
	hostedDir:    ".opencode/agents",
	mark:         generatedMark,
	nativeKey:    "permission",
	validTargets: validPermissions,
	buildData: func(role Role, targets []string) any {
		perms := make([]Permission, 0, len(targets))
		for _, target := range targets {
			perms = append(perms, Permission{Key: target, Value: "allow"})
		}
		return agentData{
			Description: role.Description,
			Mode:        role.Mode,
			Model:       role.Model,
			Permissions: perms,
			Mark:        generatedMark,
			Contract:    "## Contrato\n\n" + role.Contract,
		}
	},
}

// Install despliega el esqueleto y genera los agentes nativos de OpenCode en
// .opencode/agents/<rol>.md. Devuelve 1 si alguna fase falla.
func Install(p *paths.Project, out io.Writer) int { return install(p, opencodeRuntime, out) }

// Check verifica, sin escribir, los agentes nativos de OpenCode. Devuelve 0 si
// todo coincide y 1 si falta, no lleva la marca o difiere algún archivo.
func Check(p *paths.Project, out io.Writer) int { return check(p, opencodeRuntime, out) }
